# Generated by Django 4.0.4 on 2023-04-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterModelOptions(
            name='tableschedule',
            options={'verbose_name': 'Horario de mesa', 'verbose_name_plural': 'Horarios de mesas'},
        ),
    ]
