# Generated by Django 4.0.4 on 2023-04-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_producto_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
