# Generated by Django 4.0.4 on 2023-04-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_type_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion_producto',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre_producto',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='type',
            name='nombre',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
