# Generated by Django 4.0.4 on 2023-04-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='numero_de_telefono',
            new_name='numero_telefono',
        ),
    ]
