# Generated by Django 4.0.4 on 2023-04-18 14:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options_client_groups_client_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Celular'),
        ),
    ]
