# Generated by Django 4.0.4 on 2023-04-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_numero_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id_cliente',
            new_name='id',
        ),
    ]
