# Generated by Django 4.0.4 on 2023-04-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservacion', 'verbose_name_plural': 'Reservaciones'},
        ),
    ]
